import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        UserDao userDao = new UserDao(); // Instantiate UserDao implementation

        // Display menu
        while (true) {
            System.out.println("Menu:");
            System.out.println("1. Create User");
            System.out.println("2. Read Users");
            System.out.println("3. Update User");
            System.out.println("4. Delete User");
            System.out.println("5. Exit");
            System.out.print("Enter your choice: ");

            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline character

            switch (choice) {
                case 1:
                    createUser(userDao, scanner);
                    break;
                case 2:
                    displayUsers(userDao);
                    break;
                case 3:
                    updateUser(userDao, scanner);
                    break;
                case 4:
                    deleteUser(userDao, scanner);
                    break;
                case 5:
                    System.out.println("Exiting...");
                    scanner.close();
                    return;
                default:
                    System.out.println("Invalid choice. Please try again.");
            }
        }
    }

    private static void createUser(UserDao userDao, Scanner scanner) {
        scanner.nextLine(); // Consume newline character

        System.out.print("Enter Username: ");
        String username = scanner.nextLine();
        System.out.print("Enter Email: ");
        String email = scanner.nextLine();
        System.out.print("Enter Password: ");
        String password = scanner.nextLine();

        User newUser = new User(0, username, email, password); // ID will be generated by the database
        userDao.addUser(newUser);
        System.out.println("User created successfully.");
    }


    private static void displayUsers(UserDao userDao) {
        System.out.println("User List:");
        for (User user : userDao.getUsers()) {
            System.out.println("ID: " + user.getId() + ", Username: " + user.getUsername() + ", Email: " + user.getEmail() + ", Password: " + user.getPassword());
        }
    }

    private static void updateUser(UserDao userDao, Scanner scanner) {
        System.out.print("Enter User ID to update: ");
        int userId = scanner.nextInt();
        scanner.nextLine(); // Consume newline character

        User userToUpdate = userDao.getUserById(userId);
        if (userToUpdate != null) {
            System.out.println("User found. Enter new details:");

            System.out.print("Enter Username: ");
            String username = scanner.nextLine();
            System.out.print("Enter Email: ");
            String email = scanner.nextLine();
            System.out.print("Enter Password: ");
            String password = scanner.nextLine();

            userToUpdate.setUsername(username);
            userToUpdate.setEmail(email);
            userToUpdate.setPassword(password);

            userDao.updateUser(userToUpdate);
            System.out.println("User updated successfully.");
        } else {
            System.out.println("User not found.");
        }
    }

    private static void deleteUser(UserDao userDao, Scanner scanner) {
        System.out.print("Enter User ID to delete: ");
        int userId = scanner.nextInt();
        scanner.nextLine(); // Consume newline character

        if (userDao.deleteUser(userId)) {
            System.out.println("User deleted successfully.");
        } else {
            System.out.println("User not found.");
        }
    }
}
